FROM php:8.2-apache

# Extensiones necesarias
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Activar mod_rewrite
RUN a2enmod rewrite

# Configuración de Apache
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
